### ISSUE TITLE
[书籍][2021-4-8] rust简明教程

### ISSUE THREAD

**Issue by aresbit** [studyrs/Rustt#104]
原文标题: Tutoriel Rust

原文链接: https://blog.guillaume-gomez.fr/Rust

译文链接: 

---
法语原书作者参与rust编译器核心开发，华为Principal engineer

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
>  *[Rustt](https://rustt.org) 翻译计划，由 [StudyRust](https://studyrust.org) 社区荣誉推出*
> 
> **翻译：_该部分由 Approver 替换填写_**
> 选题：[aresbit](https://github.com/aresbit)
>
> 原文链接: https://www.rust-lang.org
```

**Comment by sunface** [comment]
抱歉，缺乏相关人才哈～
