### ISSUE TITLE
[文章][2021-12-15] Rust学习的12种误区

### ISSUE THREAD

**Issue by aresbit** [studyrs/Rustt#109]
原文标题: How not to learn Rust

原文链接: https://dystroy.org/blog/how-not-to-learn-rust/

译文链接: 

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> *本文选自 [Rust 翻译计划](https://rustt.org)，由 [StudyRust](https://studyrust.org) 荣誉推出*
> 
> **翻译：_该部分由 Approver 替换填写_**
> 选题：[Github昵称](GIthub个人链接)
>
> 原文链接: https://www.rust-lang.org
```

**Comment by sunface** [comment]
这篇文章的一些精髓，已经借鉴到 https://course.rs/first-try/sth-you-should-not-do.html
