### ISSUE TITLE
[文章][2022-03-26] Use Rust for embedded development

### ISSUE THREAD

**Issue by lxbwolf** [studyrs/Rustt#13]
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的尾部

**声明模版**

```
---
> 原文链接: https://opensource.com/article/21/10/rust-embedded-development
> 
> 翻译：[Xiaobin.Liu](https://github.com/lxbwolf)
> 选题：[Xiaobin.Liu](https://github.com/lxbwolf)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by lxbwolf** [comment]
APL @sunface

**Comment by sunface** [comment]
Approved, 选题 + 4

**Comment by sunface** [comment]
翻译 + 25

- 内容长度 10
- 质量加分 5
- 首篇奖励 10
