### ISSUE TITLE
[文章][2022-03-26] Program the real world using Rust on Raspberry Pi

### ISSUE THREAD

**Issue by lxbwolf** [studyrs/Rustt#14]
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的尾部

**声明模版**

```
---
> 原文链接: https://opensource.com/article/19/3/physical-computing-rust-raspberry-pi
> 
> 翻译：[Xiaobin.Liu](https://github.com/lxbwolf)
> 选题：[Xiaobin.Liu](https://github.com/lxbwolf)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by lxbwolf** [comment]
@sunface 申请翻译，预期完成时间 : 2022-04-02

**Comment by sunface** [comment]
Approved, 选题 + 6

**Comment by sunface** [comment]
翻译 + 15

基本分 + 10
翻译质量 + 3
翻译速度 + 2
