### ISSUE TITLE
[文章][2022-03-26] Rust 大佬给初学者的一些建议

### ISSUE THREAD

**Issue by asur4s** [studyrs/Rustt#15]
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

**声明模版**

```
---
> 原文链接: https://github.com/pretzelhammer/rust-blog/blob/master/posts/learning-rust-in-2020.md
> 
> 翻译：[Asura](https://github.com/asur4s)
>
> 选题：[Asura](https://github.com/asur4s)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by asur4s** [comment]
@sunface 申请翻译，预期完成时间 2022-04-05

**Comment by sunface** [comment]
Approved, 选题 + 6

**Comment by sunface** [comment]
`@rubot`

翻译 + 30
文章数 + 1
