### ISSUE TITLE
[文章][2022-03-28] Rust's Unsafe Pointer Types Need An Overhaul

### ISSUE THREAD

**Issue by hyuuko** [studyrs/Rustt#22]
原文标题 :Rust's Unsafe Pointer Types Need An Overhaul

原文链接: https://gankra.github.io/blah/fix-rust-pointers/

译文链接: https://github.com/studyrs/Rustt/blob/main/Articles/%5B2022-04-07%5D%20Rust%20的%20unsafe%20指针类型需要大修.md

---
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

---
**声明模版**

```
> 原文链接: https://gankra.github.io/blah/fix-rust-pointers/
> 
> 翻译：[BK0717](https://github.com/hyuuko)
> 选题：[BK0717](https://github.com/hyuuko)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by hyuuko** [comment]
@sunface 申请翻译，预期完成时间 2022-04-07

**Comment by sunface** [comment]
Approved, 选题 + 7

PS:  简单浏览了下，这个可不好翻译，加油 🤣

**Comment by sunface** [comment]
`@rubot`

翻译 + 35
