### ISSUE TITLE
[文章][2022-03-28] Rust 2024：敢于要求更多

### ISSUE THREAD

**Issue by Ch3nYe** [studyrs/Rustt#26]
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的尾部

**声明模版**

```
---
> 原文链接: https://smallcultfollowing.com/babysteps/blog/2022/02/09/dare-to-ask-for-more-rust2024/
> 
> 翻译：[YuKun Liu](https://github.com/mrxiaozhuox)
> 选题：[Ch3nYe](https://github.com/Ch3nYe)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by Ch3nYe** [comment]
@sunface 申请翻译，预期完成时间 2022-04-07

**Comment by mrxiaozhuox** [comment]
@sunface 申请翻译，预期完成时间：2022-04-01

**Comment by sunface** [comment]
Approved, 选题 + 5

**Comment by sunface** [comment]
翻译 + 27

- 基础分( 内容长度 ): 20
- 质量: 3 
- 翻译速度：4 


> 建议，适当减少人称代词的使用 :)
