### ISSUE TITLE
[书籍][2022-03-28] Discover the world of microcontrollers through Rust!

### ISSUE THREAD

**Issue by taotieren** [studyrs/Rustt#30]
**选题者须知**
- 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
- 将下面模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的尾部

**声明模版**

```
---
> 原文链接: https://github.com/rust-embedded/discovery
> 
> 翻译：_该部分由 Approver 替换填写_
> 选题：[taotieren](https://github.com/taotieren)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by sunface** [comment]
这本也是，先关闭了，以后如果有充足的人力，或者有人感兴趣，再开启～
