### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by mrxiaozhuox** [studyrs/Rustt#31]
### 英文水平和写作能力

- 雅思（5.5 - 6）很菜的qwq
- 国际部高三，即将出国读书

### 预期多久翻译一篇文章?

半个月

### QQ 号

3507952990

### 如果可以，请附上你之前比较得意的翻译作品( optional )

目前有在完成翻译 `Dioxus` 项目的中文文档。

### 你对我们有哪些预期?

希望通过这个项目学习到更多有意义东西，同时能锻炼自己各方面的能力（包括英语学习能力）

**Comment by sunface** [comment]
出国后还继续参与不 ：D

**Comment by mrxiaozhuox** [comment]
> 出国后还继续参与不 ：D

肯定参与啊哈哈

**Comment by sunface** [comment]
good, 欢迎加入
