### ISSUE TITLE
[文章][2022-03-29] Rust 背后并不是公司

### ISSUE THREAD

**Issue by mrxiaozhuox** [studyrs/Rustt#36]
原文链接: https://blog.m-ou.se/rust-is-not-a-company/

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

**声明模版**

```
---
> 原文链接: https://blog.m-ou.se/rust-is-not-a-company/
> 
> 翻译：[子殊](https://github.com/allenli178)
>
> 选题：[YuKun Liu](https://github.com/mrxiaozhuox)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by allenli178** [comment]
@mrxiaozhuox  申请翻译，预期完成时间：2022-04-05

**Comment by sunface** [comment]
下次 @ 一个 approver :)  https://github.com/orgs/studyrs/teams/rustt-approvers

**Comment by sunface** [comment]
`@rubot`

翻译 + 27
