### ISSUE TITLE
[文章][2022-03-29] 2022 年应该选择哪个 Web 框架

### ISSUE THREAD

**Issue by mrxiaozhuox** [studyrs/Rustt#37]
原文链接: https://kerkour.com/rust-web-framework-2022

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的尾部

**声明模版**

```
---
> 原文链接: https://kerkour.com/rust-web-framework-2022
> 
> 翻译：[YuKun Liu](https://github.com/mrxiaozhuox)
> 选题：[YuKun Liu](https://github.com/mrxiaozhuox)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by mrxiaozhuox** [comment]
@sunface  申请翻译，预期完成时间：2022-03-30

**Comment by sunface** [comment]
Approved, 选题 + 7

PS: 翻译速度杠杠的！

**Comment by sunface** [comment]
翻译 + 16

- 基础分( 内容长度 ): 10
- 质量: 2
- 翻译速度：4
