### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by trdthg** [studyrs/Rustt#40]
### 英文水平和写作能力

CET-6

主要是整理技术文档，自己去写作相对经验较少

### 预期多久翻译一篇文章?

半个月

### QQ 号

2820047809

### 如果可以，请附上你之前比较得意的翻译作品( optional )

无😧

一直在尝试阅读英文技术博客，但只是尝试过翻译过部分片段，并没有完整的成品

### 你对我们有哪些预期?

去年在学完 The Book 之后尝试阅读了实现链表的英文原文，一方面是之前阅读英文文章较少，另一方面自己 Rust 理解不够，读起来很吃力。希望能加入 Rust TT 帮助对 Rust 感兴趣的人降低入门门槛。自己借这个机会督促自己学习 Rust😋。

**Comment by sunface** [comment]
愿景很好～～欢迎加入。
