### ISSUE TITLE
[文章][2022-03-29] 使用 Rust 实现六边形架构

### ISSUE THREAD

**Issue by trdthg** [studyrs/Rustt#42]
原文链接: https://alexis-lozano.com/hexagonal-architecture-in-rust-1/

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

**声明模版**

```
---
> 原文链接: https://alexis-lozano.com/hexagonal-architecture-in-rust-1/
> 
> 翻译：[trdthg](https://github.com/trdthg)
>
> 选题：[trdthg](https://github.com/trdthg)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by trdthg** [comment]
@sunface  申请翻译，预期完成时间：2022-04-06

**Comment by sunface** [comment]
我看了下，这个是系列文章，是考虑翻译一整个系列嘛？

**Comment by trdthg** [comment]
是，现在已经翻译了一部分，文章整体难度不是太高

**Comment by sunface** [comment]
好。。那你要按照系列文章的格式放置文件哈

**Comment by sunface** [comment]
Approved，选题 + 15 ( 系列文章额外附加分 )

**Comment by sunface** [comment]
> > 我看了下，这个是系列文章，是考虑翻译一整个系列嘛？
> 
> 是，现在已经翻译了一部分，文章整体难度不是太高，虽然有点长就是了😀

好的，没问题，对了，提交的时候尽量一篇文章一个 PR，方便计算积分

**Comment by trdthg** [comment]
ok

**Comment by sunface** [comment]
`@rubot`

翻译 + 160
文章数 + 7
