### ISSUE TITLE
申请加入贡献者行列

### ISSUE THREAD

**Issue by allenli178** [studyrs/Rustt#44]
### 英文水平和写作能力

本人一本在读大三学生，计算机科学与技术专业，已通过英语四六级认证考试，最近有参加全国大学生英语竞赛。了解rust和前端知识。想成为一名贡献者为国内rust的发展尽一份绵薄之力。

### 预期多久翻译一篇文章?

半个月

### QQ 号

704580014

**Comment by sunface** [comment]
欢迎你加入，那样的人 :)
