### ISSUE TITLE
[文章][2022-03-29] 在 Rust 中使用 epoll 实现基本的非阻塞 IO

### ISSUE THREAD

**Issue by trdthg** [studyrs/Rustt#45]
原文链接: https://www.zupzup.org/epoll-with-rust/index.html

**翻译者须知**

- 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
- 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的顶部

**声明模版**

```
---
> 原文链接: https://www.zupzup.org/epoll-with-rust/index.html
> 
> **翻译：[BK0717](https://github.com/hyuuko)**
>
> 选题：[trdthg](https://github.com/trdthg)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by hyuuko** [comment]
@sunface 申请翻译，预期完成时间 2022-04-01

**Comment by sunface** [comment]
选题 + 7

**Comment by sunface** [comment]
`@rubot`

翻译 + 20
文章 + 1
