### ISSUE TITLE
[文章][2022-04-01] Rust中常见的集合是什么

### ISSUE THREAD

**Issue by minikiller** [studyrs/Rustt#53]
原文链接: https://medium.com/nerd-for-tech/what-are-common-collections-in-rust-e6411ece24f0

approver列表: https://guide.rustt.org/org-info/members.html#approver

**翻译者须知**

1. 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
2. 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的 **顶部**
3. 填写下面的推广渠道

**声明模版**

```
---
> 原文链接: https://medium.com/nerd-for-tech/what-are-common-collections-in-rust-e6411ece24f0
> 
> **翻译：_该部分由 Approver 替换填写_**
>
> 选题：[minikiller](https://github.com/minikiller)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by minikiller** [comment]
@sunface 申请翻译，预期完成时间 2022-04-05

**Comment by sunface** [comment]
这篇文章我觉得不好。。太简单了～～而且都是简单的代码

**Comment by minikiller** [comment]
ok，听你的！
