### ISSUE TITLE
[文章][2022-04-01] Rust 的异步是有颜色的，这并不是什么大问题

### ISSUE THREAD

**Issue by hyuuko** [studyrs/Rustt#54]
原文标题: Rust async is colored, and that’s not a big deal

原文链接: https://morestina.net/blog/1686/rust-async-is-colored

译文链接: https://github.com/studyrs/Rustt/blob/main/Articles/%5B2022-04-08%5D%20Rust%20的异步是有颜色的，这并不是什么大问题.md

---
**选题者须知**
1. 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
2. 将上面的原文链接和下面声明模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

1. 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
2. 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

```
> 原文链接: https://morestina.net/blog/1686/rust-async-is-colored
> 
> **翻译：[BK0717](https://github.com/hyuuko)**
>
> 选题：[BK0717](https://github.com/hyuuko)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by sunface** [comment]
Approved, 选题 + 7

**Comment by sunface** [comment]
`@rubot`

翻译 + 30
