### ISSUE TITLE
[文章][2022-04-02] I am a Java, C#, C or C++ developer, time to do some Rust

### ISSUE THREAD

**Issue by lxbwolf** [studyrs/Rustt#58]
原文链接: https://fasterthanli.me/articles/i-am-a-java-csharp-c-or-cplusplus-dev-time-to-do-some-rust

approver列表: https://guide.rustt.org/org-info/members.html#approver

**翻译者须知**

1. 在issue中评论：@ 一个 approver，申请翻译，并附上预期完成时间
2. 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的 **顶部**
3. 填写下面的推广渠道

**声明模版**

```
---
> 原文链接: https://fasterthanli.me/articles/i-am-a-java-csharp-c-or-cplusplus-dev-time-to-do-some-rust
> 
> **翻译：_该部分由 Approver 替换填写_**
>
> 选题：[Xiaobin.Liu](https://github.com/lxbwolf)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**推广渠道**

翻译者是否愿意在以下平台上推广你翻译的文章，是 Y ，否 N

- 微信公众号(studyrust): Y
- [知乎专栏](https://www.zhihu.com/column/c_1492085510243414016): Y

**Comment by lxbwolf** [comment]
申请翻译，预期完成时间 2022-04-10

**Comment by sunface** [comment]
`@rubot`

选题 + 8
翻译 + 40
文章 + 1
