### ISSUE TITLE
[文章][2022-04-02] 使用 Rust 和 Substrate 构建自己的区块链平台

### ISSUE THREAD

**Issue by sunface** [studyrs/Rustt#61]
原文链接: https://blog.logrocket.com/custom-blockchain-implementation-rust-substrate/

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间
2. 请翻译者在翻译后，并将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

```
---
> 原文链接: https://blog.logrocket.com/custom-blockchain-implementation-rust-substrate/
> 
> **翻译：[Akagi201](https://github.com/Akagi201)**
>
> 选题：[Sunface](https://github.com/sunface)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by Akagi201** [comment]
@sunface hi, 如何认领呀, 我可以翻译这篇. 这里回复就行吗?

**Comment by Akagi201** [comment]
预期完成时间: 2022-04-04

**Comment by sunface** [comment]
需要先[申请加入 Rustt](https://github.com/studyrs/Rustt/issues/new?assignees=&labels=kind%2Fbug&template=membership-application.yaml) 🤣

**Comment by Akagi201** [comment]
@sunface https://github.com/studyrs/Rustt/issues/68

**Comment by sunface** [comment]
`@rubot`

选题 + 8

**Comment by Akagi201** [comment]
最近事情略多, 本周末完成

**Comment by sunface** [comment]
`@rubot`

翻译 + 30
