### ISSUE TITLE
申请加入 Rustt 翻译小组 - Akagi201

### ISSUE THREAD

**Issue by Akagi201** [studyrs/Rustt#68]
### 英文水平和写作能力

国内名牌大学毕业🐶 CET-6 我可太能写了, 就是不太会说. 一对话就大脑空白不知道用什么单词.
推荐个长文翻译工具 DeepL 

### 预期多久翻译一篇文章?

半周

### QQ 号

1413031398

### 如果可以，请附上你之前比较得意的翻译作品( optional )

不喜欢用 qq, 用飞书或者微信啊.
翻译过很多东西了
最近翻译的有这个 https://crowdin.com/translate/near-docs/653/en-zhcn

### 你对我们有哪些预期?

跟进大佬们的脚步, 提升自己 Rust 专业程度.

**Comment by sunface** [comment]
太棒了，欢迎加入～
