### ISSUE TITLE
[文章][2022-04-02] Async Rust: Cooperative vs Preemptive scheduling

### ISSUE THREAD

**Issue by Akagi201** [studyrs/Rustt#70]
原文链接: https://kerkour.com/cooperative-vs-preemptive-scheduling
原文标题:  Async Rust: Cooperative vs Preemptive scheduling
译文链接：https://github.com/studyrs/Rustt/blob/main/Articles/%5B2022-04-12%5D%20异步%20Rust：协作与抢占式调度.md

---

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

---

```
> 原文链接: https://kerkour.com/cooperative-vs-preemptive-scheduling
> 
> **翻译：[trdthg](https://github.com/trdthg)**
>
> 选题：[Akagi201](https://github.com/Akagi201)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by trdthg** [comment]
@sunface 申请翻译，预计完成时间 2022-04-13

**Comment by sunface** [comment]
`@rubot`

选题 + 8

**Comment by sunface** [comment]
`@rubot`

选题 + 30

**Comment by sunface** [comment]
`@rubot`

选题 - 30

**Comment by sunface** [comment]
`@rubot`

选题 + -30

**Comment by sunface** [comment]
`@rubot`

翻译 + 30
