### ISSUE TITLE
申请加入 Rustt 翻译小组

### ISSUE THREAD

**Issue by a1393323447** [studyrs/Rustt#76]
### 英文水平和写作能力

英文水平：CET-6，读英文技术文章、文档没有压力。
写作能力：大二在读，也尝试写过一些技术文章：[编程语言自底向上](https://zhuanlan.zhihu.com/p/470477256)。我觉得自己文章写得不错，不过看的人少，提意见的人更少，也很难能对自己有很清醒的认识。

### 预期多久翻译一篇文章?

半个月

### QQ 号

1393323447

### 如果可以，请附上你之前比较得意的翻译作品( optional )

之前大多在看文章，没尝试过翻译。这是第一次翻译的成品：[Rust 交叉编译](https://github.com/studyrs/Rustt/issues/69)

### 你对我们有哪些预期?

①希望能够帮助更多的人，降低他们学习 Rust 的门槛吧。
②在这一年半的编程学习里，我很多的疑惑都是从外国的社区中找到答案。然而，不知道是不是因为我接触编程的时间太短，我总觉得中国的编程社区比较少，而且和外国相比之下也不算活跃。所以，我希望 Rustt 能够构建一个良好、活跃的 Rust 社区。

**Comment by sunface** [comment]
我看了下，你的文章写得有理有据，确实不错。互联网就是这样，好东西未必能被人发现～～

你的两点预期跟我简直不谋而合，总之，欢迎加入 ：）

**Comment by sunface** [comment]
不过我觉得就算没人看，坚持写文章对咱们自身的提高也有很大的好处。而且坚持下去，总会有越来越多的人看的，相信我.
