### ISSUE TITLE
[文章][2022-04-04] Rust 中的函数式编程

### ISSUE THREAD

**Issue by a1393323447** [studyrs/Rustt#79]
原文标题: Functional Programming in Rust

原文链接: https://kerkour.com/rust-functional-programming

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

```
---
> 原文链接: https://kerkour.com/rust-functional-programming
> 
> **翻译：[朕与将军解战袍](https://github.com/a1393323447)**
>
> 选题：[朕与将军解战袍](https://github.com/a1393323447)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by a1393323447** [comment]
申请翻译，预期完成时间 2022-04-05

**Comment by sunface** [comment]
`@rubot`

选题 + 8

**Comment by glatavento** [comment]
一处可能的 typo:

https://github.com/rustlang-cn/Rustt/blob/42863b09276017f748192f0de6412d79c1da22b2/Articles/%5B2022-04-05%5D%20Rust%20%E4%B8%AD%E7%9A%84%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BC%96%E7%A8%8B.md?plain=1#L25-L39

的原文是

```
That's why you can replace

fn add_one(x: u64) -> u64 {
  return x + 1;
}

by

fn add_one(x: u64) -> u64 {
  x + 1
}
```

replace *by* 表达的应该是用后者替代前者，所以这里应该把两段代码反过来？我的英语水平很一般，所以如果搞错了请无视

**Comment by a1393323447** [comment]
@glatavento 前一段时间是考试周，没看到留言，这一块确实有问题。
