### ISSUE TITLE
申请加入 Rust TT 翻译小组

### ISSUE THREAD

**Issue by iamazy** [studyrs/Rustt#8]
### 英文水平和写作能力

CET-4
读写基本无障碍

### 预期多久翻译一篇文章?

半个月

### QQ 号

1448588084

### 如果可以，请附上你之前比较得意的翻译作品( optional )

[libp2p 教程：使用 Rust 构建 p2p 应用](https://fucking-translation.github.io/blog/lang/rust/12-libp2p%E6%95%99%E7%A8%8B:%E4%BD%BF%E7%94%A8Rust%E6%9E%84%E5%BB%BAp2p%E5%BA%94%E7%94%A8.html#libp2p-%E6%95%99%E7%A8%8B%E4%BD%BF%E7%94%A8-rust-%E6%9E%84%E5%BB%BA-p2p-%E5%BA%94%E7%94%A8)

### 你对我们有哪些预期?

之前就有翻译的计划，但是被搁置了，希望可以重拾起来。
在学习 rust 过程中，受到社区很大的帮助，希望可以和大家一起翻译优秀的  rust 博客，对社区进行反哺

**Comment by sunface** [comment]
改名了，现在叫 Rustt，少了一个 T，哈哈。

欢迎加入 Rustt.

**Comment by sunface** [comment]
哇，你翻译了不少啊，牛～～
