### ISSUE TITLE
[文章][2022-04-04] 自修改代码

### ISSUE THREAD

**Issue by a1393323447** [studyrs/Rustt#81]
原文标题: Self Modifying Code

原文链接: https://matklad.github.io/2022/03/26/self-modifying-code.html

译文链接: https://github.com/studyrs/Rustt/blob/main/Articles/%5B2022-04-08%5D%20自修改代码.md

---
**选题者须知**
1. 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
2. 将上面的原文标题、原文链接和下面声明模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> 原文链接: https://matklad.github.io/2022/03/26/self-modifying-code.html
> 
> **翻译：[朕与将军解战袍](https://github.com/a1393323447)**
>
> 选题：[朕与将军解战袍](https://github.com/a1393323447)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by a1393323447** [comment]
申请翻译，预期完成时间 2022-04-08

**Comment by sunface** [comment]
`@rubot`

选题 + 7

**Comment by sunface** [comment]
`@rubot`

翻译 + 27

**Comment by sunface** [comment]
翻译质量很不错，赞
