### ISSUE TITLE
申请加入 Rustt 翻译小组

### ISSUE THREAD

**Issue by Ch3nYe** [studyrs/Rustt#9]
### 英文水平和写作能力

CET-6
目前在USTC读研，阅读和翻译英文文献问题不大

### 预期多久翻译一篇文章?

一个月

### QQ 号

1344098010

### 如果可以，请附上你之前比较得意的翻译作品( optional )

无😅

### 你对我们有哪些预期?

我属于刚入门Rust，希望在学习的过程中翻译一些优秀的rust文章，能以初学者的视角帮想入门的同学更好的理解和学习. 
另外，由于我本人在读研，科研压力比较大，翻译频率相比之下必定很低，但仍可提一些好选题，是否能加入Rustt请管理员判断，任何结果我都可以接受，以后也会来提交选题. 😘

**Comment by sunface** [comment]
欢迎加入，第九名成员 :)

**Comment by Ch3nYe** [comment]
😘
