### ISSUE TITLE
[文章][2022-04-06] 在 Rust 中使用 tracing 自定义日志（上）

### ISSUE THREAD

**Issue by minikiller** [studyrs/Rustt#91]
原文标题: 在 Rust 中使用 tracing 自定义日志

原文链接: https://burgers.io/custom-logging-in-rust-using-tracing

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

**声明模版**

```
---
> 原文链接: https://www.rust-lang.org
> 
> **翻译：[Sunface](https://github.com/sunface)**
>
> 选题：[minikiller](https://github.com/minikiller)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by minikiller** [comment]
@sunface 申请翻译，预期完成时间:2022-04-15

**Comment by sunface** [comment]
`@rubot` 

选题 + 9

**Comment by sunface** [comment]
`@rubot`

翻译  + 40 

PS: 上下两篇
