### ISSUE TITLE
[文章][2022-04-07] 理解 Rust 的借用检查器

### ISSUE THREAD

**Issue by lxbwolf** [studyrs/Rustt#94]
原文标题: Understanding the Rust borrow checker

原文链接: https://blog.logrocket.com/introducing-the-rust-borrow-checker/

译文链接: https://github.com/studyrs/Rustt/blob/main/Articles/%5B2022-04-07%5D%20理解%20Rust%20的借用检查器.md

---

**选题者须知**
1. 修改 issue 标题：将 `类型` 修改为为 文章、书籍、资讯 中的一个，并将 `日期` 和 `标题` 进行替换
2. 将上面的原文标题、原文链接和下面声明模版中的 `原文链接`、`选题` 替换成相应的内容

**翻译者须知**

1. 在issue中评论：申请翻译，并附上预期完成时间，等待一个 approver 来处理
2. 请翻译者在翻译后，将声明模版的 Markdown 文本加入到文章的 **顶部**

---
**声明模版**

```
> 原文链接: https://blog.logrocket.com/introducing-the-rust-borrow-checker/
> 
> **翻译：[Xiaobin.Liu](https://github.com/lxbwolf)**
>
> 选题：[Xiaobin.Liu](https://github.com/lxbwolf)
>
> 本文由 [Rustt](https://Rustt.org) 翻译，[StudyRust](https://studyrust.org) 荣誉推出
```

**Comment by sunface** [comment]
狼兄，下次先申请一下翻译哈，现在的机器人对流程是有要求的

**Comment by sunface** [comment]
`@rubot`

选题 + 8

**Comment by sunface** [comment]
`@rubot`

翻译 + 28
